name: CI/CD for NestJS Application

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}
  SERVICE_NAME: ${{ vars.SERVICE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: production
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull ${{ env.DOCKER_IMAGE }}:latest

            echo "Stopping existing container..."
            docker stop ${{ env.SERVICE_NAME }} 2>/dev/null || true
            docker rm ${{ env.SERVICE_NAME }} 2>/dev/null || true

            echo "Cleaning up unused Docker resources..."
            docker system prune -f

            echo "Starting new container..."
            docker run -d \
              --name ${{ env.SERVICE_NAME }} \
              --env-file ${{ secrets.ENV_PATH }} \
              -p ${{ vars.SERVICE_PORT }}:${{ vars.SERVICE_PORT }} \
              --restart unless-stopped \
              ${{ env.DOCKER_IMAGE }}:latest

            echo "Deployment completed successfully!"
            docker ps | grep ${{ env.SERVICE_NAME }}
