name: CI/CD for NestJS Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build --target production -t ${{ vars.SERVICE_NAME }}:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag ${{ vars.SERVICE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:latest

            sudo docker stop ${{ vars.SERVICE_NAME }} || true
            sudo docker rm ${{ vars.SERVICE_NAME }} || true
            sudo docker system prune -f

            sudo docker run -d --name ${{ vars.SERVICE_NAME }} \
              --env-file ${{ secrets.ENV_PATH }} \
              -p ${{ vars.SERVICE_PORT }}:${{ vars.SERVICE_PORT }} ${{ secrets.DOCKER_USERNAME }}/${{ vars.SERVICE_NAME }}:latest
